export type GameOdd = {
  GameOddId: number,
  Sportsbook: string,
  GameId: number,
  Created: string,
  Updated: string,
  AwayPointSpread: number,
  HomePointSpread: number,
  AwayMoneyLine: number,
  HomeMoneyLine: number,
  AwayPointSpreadPayout: number,
  HomePointSpreadPayout: number,
  OverUnder: number,
  OverPayout: number,
  UnderPayout: number,
  SportsbookId: number,
  SportsbookUrl: string,
};

export type Game = {
  _id: number,
  GameId: number,
  Season: number,
  Day: string,
  DateTime: string,
  Status: string,
  AwayTeamId: number,
  HomeTeamId: number,
  AwayTeamName: string,
  HomeTeamName: string,
  GlobalGameId: number;
  GlobalAwayTeamid: number,
  GlobalHomeTeamId: number,
  HomeTeamScore: any,
  AwayTeamScore: any,
  TotalScore: any,
  AwayRotationNumber: number,
  HomeRotationNumber: number,
  PregameOdds: GameOdd[],
  LiveOdds: GameOdd[],
  AlternateMarketPregameOdds: GameOdd[],
  Updated: string,
  GameEndDateTime: string,
};

